//! Documento `OpenAPI` generato dalle annotazioni sugli handler e sui tipi:
//! nasce dal codice, quindi non può divergere dalla *forma dei dati*. Percorso
//! e metodo di ogni operazione restano però stringhe scritte a mano
//! nell'attributo `#[utoipa::path]`: a legarli alle rotte davvero montate ci
//! pensa `documented_operations_are_all_mounted` in `tests/openapi.rs`.

use utoipa::OpenApi;
use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};

use crate::extract::SESSION_COOKIE;
use crate::routes::{
    albums, audit, auth, backup, bootstrap, credentials, duplicates, faces, flags, folders, geotag,
    groups, health, libraries, map, media, metadata, operations, permissions, persons, places,
    preferences, problems, regions, restore, search, sessions, setup, share, stacks, sync, tags,
    timeline, totp, trash, upload, users, video, viewport, ws,
};

/// Nome dello schema di sicurezza nel documento. Gli attributi
/// `#[utoipa::path(security(("session_cookie" = [])))]` devono ripeterlo come
/// letterale — le macro non accettano una costante — quindi
/// `security_requirements_name_a_declared_scheme` in `tests/openapi.rs`
/// verifica che le due scritture non divergano.
pub const SESSION_SCHEME: &str = "session_cookie";

/// Descrive l'autenticazione a cookie. Il nome del cookie non è riscritto a
/// mano: viene da `SESSION_COOKIE`, la stessa costante che l'extractor legge.
struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_default();
        components.add_security_scheme(
            SESSION_SCHEME,
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::with_description(
                SESSION_COOKIE,
                "Cookie di sessione emesso da POST /api/v1/setup e POST /api/v1/auth/login.",
            ))),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Keeppix API",
        version = "1.0.0",
        description = "API di Keeppix. Contratto congelato: solo aggiunte entro /api/v1."
    ),
    modifiers(&SecurityAddon),
    paths(
        setup::status,
        setup::create,
        auth::login,
        auth::refresh,
        auth::logout,
        auth::me,
        totp::status,
        totp::setup,
        totp::confirm,
        totp::regenerate_recovery,
        totp::disable,
        timeline::buckets,
        timeline::geometry,
        timeline::page,
        timeline::asset,
        folders::tree,
        folders::children,
        folders::relocate,
        media::thumb,
        media::preview,
        media::full,
        media::original,
        video::playback,
        video::hls,
        video::poster,
        viewport::promote,
        search::run,
        search::suggest,
        places::reverse,
        places::suggest,
        map::clusters,
        map::tiles,
        regions::list,
        regions::download,
        regions::cancel,
        regions::delete,
        search::list_saved,
        search::create_saved,
        ws::ticket,
        ws::connect,
        sync::delta,
        problems::list,
        duplicates::list,
        duplicates::members,
        duplicates::resolve,
        trash::delete,
        trash::batch_delete,
        trash::restore,
        trash::list,
        trash::empty,
        stacks::get_members,
        stacks::set_primary,
        metadata::effective,
        metadata::apply,
        metadata::apply_batch,
        metadata::shift_taken_at,
        metadata::preview_timezones,
        metadata::apply_timezones,
        metadata::undo_batch,
        geotag::copy_location,
        geotag::import_gpx,
        flags::get,
        flags::set,
        flags::batch_set,
        libraries::list,
        libraries::create,
        libraries::get,
        libraries::patch,
        libraries::delete,
        libraries::preview,
        libraries::start_scan,
        libraries::scan_status,
        libraries::storage,
        libraries::probe,
        users::list,
        users::create,
        users::patch,
        users::disable,
        users::enable,
        users::change_password,
        users::set_home,
        users::delete_home,
        preferences::get,
        preferences::patch,
        credentials::create,
        credentials::list,
        credentials::revoke,
        sessions::list,
        sessions::revoke,
        sessions::revoke_others,
        health::get,
        bootstrap::get,
        operations::cancel,
        albums::create,
        albums::list,
        albums::get,
        albums::patch,
        albums::delete,
        albums::add_asset,
        albums::remove_asset,
        albums::reorder_asset,
        albums::list_assets,
        albums::refresh,
        tags::list,
        tags::create,
        tags::get,
        tags::patch,
        tags::delete,
        tags::list_proposals,
        tags::confirm_proposal,
        tags::reject_proposal,
        tags::confirm_all_proposals,
        tags::reject_all_proposals,
        faces::list_for_asset,
        faces::list_proposals,
        faces::assign,
        faces::reject,
        faces::confirm_proposal,
        faces::confirm_all_proposals,
        faces::reject_all_proposals,
        faces::delete_all_data,
        persons::list,
        persons::create,
        persons::get,
        persons::patch,
        persons::delete,
        persons::merge,
        persons::separate,
        persons::list_groups,
        persons::create_group,
        persons::patch_group,
        persons::delete_group,
        persons::list_group_members,
        persons::add_group_member,
        persons::remove_group_member,
        groups::list,
        groups::create,
        groups::patch,
        groups::delete,
        groups::list_members,
        groups::add_member,
        groups::remove_member,
        permissions::list,
        permissions::grant,
        permissions::patch,
        permissions::revoke,
        permissions::explain,
        permissions::shared_with_me,
        share::create_link,
        share::revoke_link,
        share::list_links,
        share::approve_guest_upload,
        share::public_info,
        share::public_auth,
        share::public_assets,
        share::public_upload,
        audit::list,
        backup::get_preferences,
        backup::put_preferences,
        backup::list_destinations,
        backup::create_destination,
        backup::delete_destination,
        backup::test_destination,
        backup::list_runs,
        backup::run_now,
        restore::inspect,
        restore::restore,
        upload::check,
        upload::create,
        upload::head,
        upload::patch,
    ),
    // Elenco ridondante: utoipa raccoglie da sé gli schemi referenziati dalle
    // operazioni (verificato — togliendo una voce il documento non cambia di un
    // byte). Vale come indice leggibile dei tipi pubblici, non come
    // configurazione: aggiungere qui un tipo che nessuna operazione referenzia
    // non lo fa comparire nel documento.
    components(schemas(
        auth::UserView,
        auth::LoginRequest,
        auth::LoginResponse,
        auth::MeResponse,
        totp::TotpStatusView,
        totp::TotpSetupView,
        totp::TotpCodeRequest,
        totp::TotpRecoveryCodesView,
        setup::SetupStatus,
        setup::SetupRequest,
        setup::SetupResponse,
        timeline::MonthBucketView,
        timeline::TimelinePage,
        timeline::AssetView,
        folders::FolderView,
        folders::FolderChildren,
        viewport::ViewportRequest,
        search::SearchRequest,
        search::SearchPage,
        search::SuggestResponse,
        places::PlaceView,
        map::MapClusterView,
        regions::RegionView,
        regions::DownloadRegionRequest,
        search::SavedSearchRequest,
        search::SavedSearchView,
        ws::TicketResponse,
        sync::DeltaView,
        problems::ProblemsView,
        duplicates::DuplicateGroupView,
        duplicates::ResolveDuplicateRequest,
        duplicates::ResolveDuplicateResponse,
        video::PlaybackResponse,
        trash::DeleteAssetRequest,
        trash::BatchDeleteRequest,
        trash::TrashListPage,
        trash::TrashItemView,
        trash::EmptyTrashResponse,
        stacks::StackView,
        stacks::StackMemberView,
        metadata::GeoPointView,
        metadata::EffectiveMetadataView,
        metadata::MetadataPatchRequest,
        metadata::BatchApplyRequest,
        metadata::BatchShiftRequest,
        metadata::RecalculateTimezonesRequest,
        metadata::TimezoneExampleView,
        metadata::TimezonePreviewView,
        metadata::TimezoneApplyView,
        geotag::CopyLocationRequest,
        geotag::ImportGpxRequest,
        flags::AssetFlagsBody,
        flags::BatchFlagsRequest,
        crate::bulk::BulkOutcome,
        crate::bulk::BulkFailure,
        crate::bulk::FailureReason,
        libraries::LibraryView,
        libraries::CreateLibraryRequest,
        libraries::PatchLibraryRequest,
        libraries::DeleteLibraryResponse,
        libraries::PreviewResponse,
        libraries::ScanAccepted,
        libraries::ScanStatusView,
        libraries::LibraryStorageView,
        users::CreateUserRequest,
        users::PatchUserRequest,
        users::ChangePasswordRequest,
        users::SetHomeRequest,
        users::HomeView,
        preferences::UserPreferencesView,
        preferences::GridDensityView,
        preferences::NotificationPreferencesView,
        credentials::CreateAppPasswordRequest,
        credentials::AppPasswordView,
        credentials::AppPasswordCreatedView,
        sessions::SessionView,
        crate::problem::Problem,
        health::Health,
        bootstrap::BootstrapResponse,
        bootstrap::BadgeCountsView,
        albums::AlbumView,
        albums::AlbumAssetView,
        albums::CreateAlbumBody,
        albums::PatchAlbumBody,
        albums::ReorderBody,
        tags::TagView,
        tags::CreateTagRequest,
        tags::PatchTagRequest,
        tags::ProposalView,
        faces::FaceView,
        faces::FaceBBoxView,
        faces::AssignFaceRequest,
        crate::bulk::FaceBulkOutcome,
        crate::bulk::FaceBulkFailure,
        persons::PersonView,
        persons::CreatePersonRequest,
        persons::PatchPersonRequest,
        persons::MergePersonsRequest,
        persons::SeparatePersonRequest,
        persons::PersonGroupView,
        persons::CreatePersonGroupRequest,
        persons::RenamePersonGroupRequest,
        groups::GroupView,
        groups::GroupMemberView,
        groups::CreateGroupRequest,
        groups::PatchGroupRequest,
        permissions::PermissionGrantView,
        permissions::GrantRequest,
        permissions::GrantSummaryView,
        permissions::PatchPermissionRequest,
        permissions::ExplainView,
        permissions::ExplainChainLinkView,
        permissions::SharedWithMeView,
        share::CreateLinkRequest,
        share::CreateLinkResponse,
        share::LinkView,
        share::ShareInfoResponse,
        share::ShareAuthRequest,
        share::SharedContentResponse,
        share::GuestUploadResponse,
        audit::AuditEntryView,
        backup::BackupPreferencesView,
        backup::BackupPreferencesPatch,
        backup::DestinationView,
        backup::NewDestinationRequest,
        backup::RunView,
        restore::InspectRequest,
        restore::InspectResponse,
        restore::RestoreRequest,
        restore::RestoreComponents,
        restore::RestorePreview,
        upload::CheckRequest,
        upload::CheckResponse,
        upload::CreateSessionRequest,
        upload::CreateSessionResponse,
        upload::UploadCompleteResponse,
    )),
    tags(
        (name = "setup", description = "Configurazione iniziale dell'istanza"),
        (name = "auth", description = "Autenticazione e sessioni"),
        (name = "users", description = "Gestione utenti"),
        (name = "timeline", description = "Bucket mensili e pagine keyset"),
        (name = "folders", description = "Albero delle cartelle"),
        (name = "media", description = "Miniature, preview e originali"),
        (name = "search", description = "Ricerca da AST e ricerche salvate"),
        (name = "places", description = "Geocoding locale GeoNames"),
        (name = "map", description = "Cluster geografici con visibilità applicata"),
        (name = "events", description = "WebSocket di notifica"),
        (name = "library", description = "Problemi e duplicati"),
        (name = "libraries", description = "Librerie e percorsi indicizzati"),
        (name = "trash", description = "Cancellazione a tre opzioni e ripristino"),
        (name = "metadata", description = "Metadati effettivi ed editing in blocco"),
        (name = "flags", description = "Voti di culling per utente: rating, pick, etichetta colore"),
        (name = "health", description = "Liveness check"),
        (name = "operations", description = "Annullamento delle operazioni lunghe"),
        (name = "albums", description = "Album virtuali: CRUD e gestione asset"),
        (name = "tags", description = "Vocabolario condiviso di tag e categorie"),
        (name = "faces", description = "Volti rilevati, coda di revisione"),
        (name = "persons", description = "Persone e gruppi di persone fotografate"),
        (name = "groups", description = "Gruppi utente"),
        (name = "permissions", description = "Pannello permessi: elenco, concessione, revoca, explain"),
        (name = "share", description = "Link pubblici e accesso guest"),
        (name = "audit", description = "Registro audit append-only"),
        (name = "backup", description = "Wizard di backup"),
        (name = "restore", description = "Wizard di restore"),
        (name = "upload", description = "Sessioni di upload riprendibili in stile tus")
    )
)]
pub struct ApiDoc;

/// Serve il documento su `GET /api/openapi.json`.
pub async fn serve() -> axum::Json<utoipa::openapi::OpenApi> {
    axum::Json(ApiDoc::openapi())
}
