//! `OpenAPI` document generated from the annotations on handlers and types:
//! it's derived from the code, so it can't diverge from the *shape of the
//! data*. The path and method of each operation, though, remain hand-written
//! strings in the `#[utoipa::path]` attribute: tying them to the routes
//! actually mounted is `documented_operations_are_all_mounted`'s job, in
//! `tests/openapi.rs`.

use utoipa::OpenApi;
use utoipa::openapi::security::{ApiKey, ApiKeyValue, SecurityScheme};

use crate::extract::SESSION_COOKIE;
use crate::routes::{
    albums, asset_move, audit, auth, backup, bootstrap, credentials, culling, duplicates, faces,
    flags, folders, geotag, groups, health, libraries, map, media, metadata, operations,
    permissions, persons, places, preferences, problems, regions, rename, restore, search,
    sessions, setup, share, stacks, sync, tags, timeline, totp, trash, upload, users, video,
    viewport, ws,
};

/// Name of the security scheme in the document. The
/// `#[utoipa::path(security(("session_cookie" = [])))]` attributes have to
/// repeat it as a literal — the macros don't accept a constant — so
/// `security_requirements_name_a_declared_scheme` in `tests/openapi.rs`
/// verifies the two spellings don't diverge.
pub const SESSION_SCHEME: &str = "session_cookie";

/// Describes cookie authentication. The cookie name isn't rewritten by
/// hand: it comes from `SESSION_COOKIE`, the same constant the extractor
/// reads.
struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_default();
        components.add_security_scheme(
            SESSION_SCHEME,
            SecurityScheme::ApiKey(ApiKey::Cookie(ApiKeyValue::with_description(
                SESSION_COOKIE,
                "Session cookie issued by POST /api/v1/setup and POST /api/v1/auth/login.",
            ))),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Keeppix API",
        version = "1.0.0",
        description = "Keeppix API. Frozen contract: additions only within /api/v1."
    ),
    modifiers(&SecurityAddon),
    paths(
        setup::status,
        setup::create,
        auth::login,
        auth::refresh,
        auth::logout,
        auth::me,
        totp::status,
        totp::setup,
        totp::confirm,
        totp::regenerate_recovery,
        totp::disable,
        timeline::buckets,
        timeline::geometry,
        timeline::page,
        timeline::asset,
        folders::tree,
        folders::children,
        folders::relocate,
        media::thumb,
        media::preview,
        media::full,
        media::original,
        video::playback,
        video::hls,
        video::poster,
        viewport::promote,
        search::run,
        search::suggest,
        places::reverse,
        places::suggest,
        map::clusters,
        map::tiles,
        regions::list,
        regions::download,
        regions::cancel,
        regions::delete,
        search::list_saved,
        search::create_saved,
        ws::ticket,
        ws::connect,
        sync::delta,
        problems::list,
        duplicates::list,
        duplicates::members,
        duplicates::resolve,
        trash::delete,
        trash::batch_delete,
        trash::restore,
        trash::list,
        trash::empty,
        stacks::get_members,
        stacks::set_primary,
        metadata::effective,
        metadata::apply,
        metadata::apply_batch,
        metadata::shift_taken_at,
        metadata::preview_timezones,
        metadata::apply_timezones,
        metadata::undo_batch,
        rename::preview,
        rename::apply_batch,
        rename::undo_batch,
        asset_move::batch_move,
        geotag::copy_location,
        geotag::import_gpx,
        flags::get,
        flags::set,
        flags::batch_set,
        libraries::list,
        libraries::create,
        libraries::get,
        libraries::patch,
        libraries::delete,
        libraries::preview,
        libraries::start_scan,
        libraries::scan_status,
        libraries::storage,
        libraries::probe,
        libraries::set_culling_root,
        culling::list_lots,
        culling::pick,
        culling::empty_skipped,
        users::list,
        users::create,
        users::patch,
        users::disable,
        users::enable,
        users::change_password,
        users::set_home,
        users::delete_home,
        preferences::get,
        preferences::patch,
        credentials::create,
        credentials::list,
        credentials::revoke,
        sessions::list,
        sessions::revoke,
        sessions::revoke_others,
        health::get,
        bootstrap::get,
        operations::cancel,
        albums::create,
        albums::list,
        albums::get,
        albums::patch,
        albums::delete,
        albums::add_asset,
        albums::remove_asset,
        albums::reorder_asset,
        albums::list_assets,
        albums::refresh,
        albums::list_for_asset,
        tags::list,
        tags::create,
        tags::get,
        tags::patch,
        tags::delete,
        tags::list_proposals,
        tags::confirm_proposal,
        tags::reject_proposal,
        tags::remove_confirmed_tag,
        tags::confirm_all_proposals,
        tags::reject_all_proposals,
        tags::assign_batch,
        tags::unassign_batch,
        tags::list_tags_for_asset,
        faces::list_for_asset,
        faces::list_proposals,
        faces::assign,
        faces::reject,
        faces::confirm_proposal,
        faces::confirm_all_proposals,
        faces::reject_all_proposals,
        faces::delete_all_data,
        persons::list,
        persons::create,
        persons::get,
        persons::patch,
        persons::delete,
        persons::merge,
        persons::separate,
        persons::list_groups,
        persons::create_group,
        persons::patch_group,
        persons::delete_group,
        persons::list_group_members,
        persons::add_group_member,
        persons::remove_group_member,
        groups::list,
        groups::create,
        groups::patch,
        groups::delete,
        groups::list_members,
        groups::add_member,
        groups::remove_member,
        permissions::list,
        permissions::grant,
        permissions::patch,
        permissions::revoke,
        permissions::explain,
        permissions::shared_with_me,
        share::create_link,
        share::revoke_link,
        share::list_links,
        share::approve_guest_upload,
        share::public_info,
        share::public_auth,
        share::public_assets,
        share::public_upload,
        audit::list,
        backup::get_preferences,
        backup::put_preferences,
        backup::list_destinations,
        backup::create_destination,
        backup::delete_destination,
        backup::test_destination,
        backup::list_runs,
        backup::run_now,
        restore::inspect,
        restore::restore,
        upload::check,
        upload::create,
        upload::head,
        upload::patch,
    ),
    // Redundant list: utoipa collects the schemas referenced by operations
    // on its own (verified — removing an entry doesn't change the document
    // by a single byte). This serves as a readable index of public types,
    // not as configuration: adding a type here that no operation
    // references won't make it appear in the document.
    components(schemas(
        auth::UserView,
        auth::LoginRequest,
        auth::LoginResponse,
        auth::MeResponse,
        totp::TotpStatusView,
        totp::TotpSetupView,
        totp::TotpCodeRequest,
        totp::TotpRecoveryCodesView,
        setup::SetupStatus,
        setup::SetupRequest,
        setup::SetupResponse,
        timeline::MonthBucketView,
        timeline::TimelinePage,
        timeline::AssetView,
        timeline::AssetTagBadgeView,
        timeline::AssetFaceBadgeView,
        timeline::AssetExifDetailView,
        folders::FolderView,
        folders::FolderChildren,
        viewport::ViewportRequest,
        search::SearchRequest,
        search::SearchPage,
        search::SuggestResponse,
        places::PlaceView,
        map::MapClusterView,
        regions::RegionView,
        regions::DownloadRegionRequest,
        search::SavedSearchRequest,
        search::SavedSearchView,
        ws::TicketResponse,
        sync::DeltaView,
        problems::ProblemsView,
        duplicates::DuplicateGroupView,
        duplicates::ResolveDuplicateRequest,
        duplicates::ResolveDuplicateResponse,
        video::PlaybackResponse,
        trash::DeleteAssetRequest,
        trash::BatchDeleteRequest,
        trash::TrashListPage,
        trash::TrashItemView,
        trash::EmptyTrashResponse,
        stacks::StackView,
        stacks::StackMemberView,
        metadata::GeoPointView,
        metadata::EffectiveMetadataView,
        metadata::MetadataPatchRequest,
        metadata::BatchApplyRequest,
        metadata::BatchShiftRequest,
        metadata::RecalculateTimezonesRequest,
        metadata::TimezoneExampleView,
        metadata::TimezonePreviewView,
        metadata::TimezoneApplyView,
        rename::RenameBatchRequest,
        rename::RenamePreviewItemView,
        rename::RenameOperationOutcome,
        asset_move::BatchMoveRequest,
        geotag::CopyLocationRequest,
        geotag::ImportGpxRequest,
        flags::AssetFlagsBody,
        flags::BatchFlagsRequest,
        crate::bulk::BulkOutcome,
        crate::bulk::BulkFailure,
        crate::bulk::FailureReason,
        libraries::LibraryView,
        libraries::CreateLibraryRequest,
        libraries::PatchLibraryRequest,
        libraries::DeleteLibraryResponse,
        libraries::PreviewResponse,
        libraries::ScanAccepted,
        libraries::ScanStatusView,
        libraries::LibraryStorageView,
        libraries::PatchCullingRootRequest,
        culling::CullingLotView,
        culling::PickRequest,
        users::CreateUserRequest,
        users::PatchUserRequest,
        users::ChangePasswordRequest,
        users::SetHomeRequest,
        users::HomeView,
        preferences::UserPreferencesView,
        preferences::GridDensityView,
        preferences::NotificationPreferencesView,
        credentials::CreateAppPasswordRequest,
        credentials::AppPasswordView,
        credentials::AppPasswordCreatedView,
        sessions::SessionView,
        crate::problem::Problem,
        health::Health,
        bootstrap::BootstrapResponse,
        bootstrap::BadgeCountsView,
        albums::AlbumView,
        albums::AlbumAssetView,
        albums::CreateAlbumBody,
        albums::PatchAlbumBody,
        albums::ReorderBody,
        albums::AlbumBadgeView,
        tags::TagView,
        tags::CreateTagRequest,
        tags::PatchTagRequest,
        tags::ProposalView,
        tags::BatchAssignRequest,
        tags::AssetTagDetailView,
        faces::FaceView,
        faces::FaceBBoxView,
        faces::AssignFaceRequest,
        crate::bulk::FaceBulkOutcome,
        crate::bulk::FaceBulkFailure,
        persons::PersonView,
        persons::CreatePersonRequest,
        persons::PatchPersonRequest,
        persons::MergePersonsRequest,
        persons::SeparatePersonRequest,
        persons::PersonGroupView,
        persons::CreatePersonGroupRequest,
        persons::RenamePersonGroupRequest,
        groups::GroupView,
        groups::GroupMemberView,
        groups::CreateGroupRequest,
        groups::PatchGroupRequest,
        permissions::PermissionGrantView,
        permissions::GrantRequest,
        permissions::GrantSummaryView,
        permissions::PatchPermissionRequest,
        permissions::ExplainView,
        permissions::ExplainChainLinkView,
        permissions::SharedWithMeView,
        share::CreateLinkRequest,
        share::CreateLinkResponse,
        share::LinkView,
        share::ShareInfoResponse,
        share::ShareAuthRequest,
        share::SharedContentResponse,
        share::PublicAssetView,
        share::GuestUploadResponse,
        audit::AuditEntryView,
        backup::BackupPreferencesView,
        backup::BackupPreferencesPatch,
        backup::DestinationView,
        backup::NewDestinationRequest,
        backup::RunView,
        restore::InspectRequest,
        restore::InspectResponse,
        restore::RestoreRequest,
        restore::RestoreComponents,
        restore::RestorePreview,
        upload::CheckRequest,
        upload::CheckResponse,
        upload::CreateSessionRequest,
        upload::CreateSessionResponse,
        upload::UploadCompleteResponse,
    )),
    tags(
        (name = "setup", description = "Initial instance configuration"),
        (name = "auth", description = "Authentication and sessions"),
        (name = "users", description = "User management"),
        (name = "timeline", description = "Monthly buckets and keyset pages"),
        (name = "folders", description = "Folder tree"),
        (name = "media", description = "Thumbnails, previews, and originals"),
        (name = "search", description = "AST-based search and saved searches"),
        (name = "places", description = "Local GeoNames geocoding"),
        (name = "map", description = "Geographic clusters with visibility applied"),
        (name = "events", description = "Notification WebSocket"),
        (name = "library", description = "Problems and duplicates"),
        (name = "libraries", description = "Libraries and indexed paths"),
        (name = "trash", description = "Three-option deletion and restore"),
        (name = "metadata", description = "Effective metadata and bulk editing"),
        (name = "flags", description = "Per-user culling votes: rating, pick, color label"),
        (name = "culling", description = "Folder culling lots: listing, physical pick/reject, empty rejected"),
        (name = "health", description = "Liveness check"),
        (name = "operations", description = "Cancellation of long-running operations"),
        (name = "albums", description = "Virtual albums: CRUD and asset management"),
        (name = "tags", description = "Shared vocabulary of tags and categories"),
        (name = "faces", description = "Detected faces, review queue"),
        (name = "persons", description = "People and groups of photographed people"),
        (name = "groups", description = "User groups"),
        (name = "permissions", description = "Permissions panel: list, grant, revoke, explain"),
        (name = "share", description = "Public links and guest access"),
        (name = "audit", description = "Append-only audit log"),
        (name = "backup", description = "Backup wizard"),
        (name = "restore", description = "Restore wizard"),
        (name = "upload", description = "tus-style resumable upload sessions")
    )
)]
pub struct ApiDoc;

/// Serves the document at `GET /api/openapi.json`.
pub async fn serve() -> axum::Json<utoipa::openapi::OpenApi> {
    axum::Json(ApiDoc::openapi())
}
