use axum::body::Body;
use axum::http::{Request, StatusCode};
use keeppix_test_support::assert_security_headers;
use tower::ServiceExt as _;

/// The test only runs when the frontend has been built: in CI, the frontend
/// build precedes the backend build.
fn frontend_built() -> bool {
    std::path::Path::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../frontend/dist/index.html"
    ))
    .exists()
}

#[tokio::test]
#[allow(clippy::unwrap_used)]
async fn index_is_served_at_root() {
    if !frontend_built() {
        eprintln!("frontend/dist missing: skipping test");
        return;
    }

    let app = keeppix_server::embed::mount_stateless();
    let response = app
        .oneshot(Request::builder().uri("/").body(Body::empty()).unwrap())
        .await
        .unwrap();

    assert_eq!(response.status(), StatusCode::OK);
    assert_eq!(response.headers().get("cache-control").unwrap(), "no-cache");
    // The SPA fallback serves precisely the document that boots the entire
    // application: if it comes out without security headers, Keeppix's main
    // page runs without CSP in production while `/health` has it (see the
    // comment on `keeppix_api::with_common_layers`).
    assert_security_headers(response.headers());

    // Proves that the embed actually contains the files built by Vite, not
    // an empty body with status 200: an empty embed would silently degrade
    // to "200 with no content" on every path.
    let body = http_body_util::BodyExt::collect(response.into_body())
        .await
        .unwrap()
        .to_bytes();
    let html = String::from_utf8_lossy(&body);
    assert!(
        html.contains("<script"),
        "embedded index.html must contain the bundle generated by Vite"
    );
}

#[tokio::test]
#[allow(clippy::unwrap_used)]
async fn client_routes_fall_back_to_index() {
    if !frontend_built() {
        eprintln!("frontend/dist missing: skipping test");
        return;
    }

    let app = keeppix_server::embed::mount_stateless();
    let response = app
        .oneshot(
            Request::builder()
                .uri("/albums/42")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(response.status(), StatusCode::OK, "routing is client-side");
    assert_security_headers(response.headers());
}

#[tokio::test]
#[allow(clippy::unwrap_used)]
async fn api_paths_never_fall_back_to_index() {
    if !frontend_built() {
        eprintln!("frontend/dist missing: skipping test");
        return;
    }

    let app = keeppix_server::embed::mount_stateless();
    let response = app
        .oneshot(
            Request::builder()
                .uri("/api/v1/nope")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(response.status(), StatusCode::NOT_FOUND);
    assert_eq!(
        response.headers().get("content-type").unwrap(),
        "application/problem+json",
        "an API client must never receive HTML"
    );
}

#[tokio::test]
#[allow(clippy::unwrap_used)]
async fn media_and_dav_paths_never_fall_back_to_index() {
    if !frontend_built() {
        eprintln!("frontend/dist missing: skipping test");
        return;
    }

    let app = keeppix_server::embed::mount_stateless();
    for path in ["/media/thumb/deadbeef", "/dav/foo"] {
        let response = app
            .clone()
            .oneshot(Request::builder().uri(path).body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(response.status(), StatusCode::NOT_FOUND, "{path}");
        assert_eq!(
            response.headers().get("content-type").unwrap(),
            "application/problem+json",
            "{path} must not receive index.html"
        );
    }
}

#[tokio::test]
#[allow(clippy::unwrap_used, clippy::expect_used)]
async fn assets_are_served_as_immutable() {
    if !frontend_built() {
        eprintln!("frontend/dist missing: skipping test");
        return;
    }

    // The exact bundle filename contains a hash generated by Vite on every
    // build and isn't predictable; the only stable thing is the folder.
    let asset_path = std::fs::read_dir(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../frontend/dist/assets"
    ))
    .unwrap()
    .filter_map(Result::ok)
    .find_map(|entry| {
        let name = entry.file_name().into_string().ok()?;
        std::path::Path::new(&name)
            .extension()
            .is_some_and(|ext| ext.eq_ignore_ascii_case("js"))
            .then_some(name)
    })
    .expect("the Vite build produces at least one .js bundle");

    let app = keeppix_server::embed::mount_stateless();
    let response = app
        .oneshot(
            Request::builder()
                .uri(format!("/assets/{asset_path}"))
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(response.status(), StatusCode::OK);
    // This is also the counter-proof for the `Cache-Control: private` layer
    // added in `with_common_layers`: it uses `if_not_present`, so the
    // immutable policy set by the handler must survive. With `overriding`
    // this test would fail — and the first bullet of §9.4 (hashed assets
    // never requested twice) would be undone by its own last line.
    assert_eq!(
        response.headers().get("cache-control").unwrap(),
        "public, max-age=31536000, immutable"
    );
}
