[package]
name = "keeppix-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "keeppix_server"
path = "src/lib.rs"

[[bin]]
name = "keeppix"
path = "src/main.rs"

[dependencies]
keeppix-domain = { path = "../keeppix-domain" }
keeppix-db = { path = "../keeppix-db" }
keeppix-api = { path = "../keeppix-api" }
keeppix-jobs = { path = "../keeppix-jobs" }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
figment = { version = "0.10.19", features = ["toml", "env"] }
clap = { version = "4.6.6", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }
axum = "0.8.9"
tower-http = { version = "0.7.0", features = ["fs", "trace", "compression-br", "set-header", "cors"] }
serde.workspace = true
rust-embed = { version = "8.12.0", features = ["interpolate-folder-path"] }
mime_guess = "2.0.5"
chrono = { workspace = true, features = ["serde"] }

[lints]
workspace = true

[dev-dependencies]
http-body-util = "0.1.5"
keeppix-test-support = { path = "../keeppix-test-support" }
serial_test = "3"
tempfile = "3.27.0"
tower = { version = "0.5.3", features = ["util"] }
