/**
 * RFC 9457 error. `type` is the stable code to branch on.
 *
 * Fields are assigned in the constructor body, not as parameter
 * properties: that syntax requires runtime-emitted code and is forbidden
 * by `erasableSyntaxOnly` in the tsconfig generated by the current
 * template.
 */
export class ApiProblem extends Error {
  readonly type: string
  readonly title: string
  readonly status: number
  readonly detail?: string

  constructor(type: string, title: string, status: number, detail?: string) {
    super(`${type}: ${title}`)
    this.name = 'ApiProblem'
    this.type = type
    this.title = title
    this.status = status
    this.detail = detail
  }
}

/**
 * JSON call to the API. Always sends cookies and a custom header. The
 * `x-keeppix-client` header is the client-side half of the CSRF defense:
 * a hostile site's HTML form can't set a custom header. The backend
 * **requires it** on mutations (POST/PUT/PATCH/DELETE) and responds
 * `403 keeppix/csrf-check-failed` if it's missing: see
 * `crates/keeppix-api/src/csrf.rs`. Every API call must therefore go
 * through here — a hand-written `fetch` on a mutation would be rejected.
 */
export async function apiFetch<T = unknown>(
  path: string,
  init: RequestInit = {}
): Promise<T> {
  const response = await fetch(path, {
    ...init,
    credentials: 'same-origin',
    headers: {
      'content-type': 'application/json',
      'x-keeppix-client': 'web',
      ...(init.headers ?? {})
    }
  })

  if (response.status === 204) {
    return null as T
  }

  if (!response.ok) {
    await throwProblem(response)
  }

  return (await response.json()) as T
}

/**
 * Extracted from `apiFetch` for a binary endpoint (`/timeline/geometry`)
 * that can't go through the `.json()` branch above but still needs to
 * recognize the same `application/problem+json` body on 401/403.
 */
export async function throwProblem(response: Response): Promise<never> {
  const contentType = response.headers.get('content-type') ?? ''
  if (contentType.includes('application/problem+json')) {
    const problem = await response.json()
    throw new ApiProblem(problem.type, problem.title, problem.status, problem.detail)
  }
  throw new ApiProblem('keeppix/unexpected', response.statusText, response.status)
}

/**
 * A view that loads data on mount can't tell, from a generic `catch`, an
 * expired session apart from a real failure — and showing "unexpected
 * error" for a 401 sends the user to reload instead of logging in again.
 * Views check this explicitly and redirect themselves: see
 * `TimelineView.signOut` for the same `/login` redirect pattern.
 */
export function isUnauthenticated(error: unknown): boolean {
  return error instanceof ApiProblem && error.status === 401
}
