[package]
name = "keeppix-jobs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
keeppix-domain = { path = "../keeppix-domain" }
keeppix-db = { path = "../keeppix-db" }
keeppix-media = { path = "../keeppix-media" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls-ring", "postgres"] }
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
uuid.workspace = true
