[package]
name = "keeppix-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
keeppix-domain = { path = "../keeppix-domain" }
chrono.workspace = true
serde_json.workspace = true
walkdir = "2"
exif = { package = "kamadak-exif", version = "0.6.1" }

[lints]
workspace = true
