[package]
name = "keeppix-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
keeppix-domain = { path = "../keeppix-domain" }
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["cookie"] }
tower-http = { version = "0.7.0", features = ["set-header", "trace", "compression-br", "compression-gzip", "cors"] }
tower = "0.5.3"
keeppix-db = { version = "0.1.0", path = "../keeppix-db" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
http = "1.5.0"
time = "0.3.55"
utoipa = { version = "5.5.0", features = ["axum_extras", "chrono", "uuid"] }

[lints]
workspace = true

[dev-dependencies]
http-body-util = "0.1.5"
keeppix-test-support = { path = "../keeppix-test-support" }
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls", "cookies"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls-ring", "postgres"] }
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
tower = { version = "0.5.3", features = ["util"] }
uuid.workspace = true
