[package]
name = "keeppix-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
argon2 = { version = "0.5.3", features = ["std"] }
sha2 = "0.11.0"
rand = { version = "0.10.2", features = ["std", "std_rng"] }
base64 = "0.23.1"

[lints]
workspace = true
